import { test, expect } from '@playwright/test';
import { mockMenu, openIdentification } from './helpers';

test('registration has independent password toggles and only sends matching passwords of at least six characters', async ({ page }) => {
  await mockMenu(page);
  await page.route('**/api/branch-payment-method-settings/branch/7', route => route.fulfill({ json: null }));
  await page.route('**/api/branch-payment-method-settings/resolve*', route => route.fulfill({ json: null }));
  let requests = 0;
  let submittedPassword = '';
  await page.route('**/api/storefront/branches/*/customers', route => {
    requests++;
    submittedPassword = route.request().postDataJSON().password;
    return route.fulfill({ json: { id: 1, companyId: 1 } });
  });
  await page.route('**/api/storefront/customer/addresses', route => route.fulfill({ json: { id: 1, companyId: 1 } }));
  await page.route('https://viacep.com.br/**', route => route.fulfill({ json: { logradouro: 'Rua Teste', bairro: 'Centro', localidade: 'São Paulo', uf: 'SP' } }));
  await openIdentification(page);
  const auth = page.getByTestId('storefront-auth-modal');
  await auth.getByRole('tab', { name: 'Novo Cliente' }).click();
  const password = auth.getByLabel('Senha', { exact: true });
  const confirmation = auth.getByLabel('Confirmar Senha', { exact: true });
  await password.fill('abcdef');
  await confirmation.fill('abcdef ');
  await auth.getByRole('button', { name: 'Mostrar senha', exact: true }).click();
  await expect(password).toHaveAttribute('type', 'text');
  await expect(confirmation).toHaveAttribute('type', 'password');
  await auth.getByRole('button', { name: 'Mostrar confirmar senha', exact: true }).click();
  await expect(confirmation).toHaveAttribute('type', 'text');
  await auth.getByRole('button', { name: 'Ocultar senha', exact: true }).click();
  await expect(password).toHaveAttribute('type', 'password');
  const submit = auth.getByRole('button', { name: 'Cadastrar e Enviar Pedido' });
  await submit.click();
  await expect(auth.getByRole('alert')).toHaveText('As senhas não coincidem.');
  expect(requests).toBe(0);
  await password.fill('12345');
  await confirmation.fill('12345');
  await submit.click();
  await expect(auth.getByRole('alert')).toHaveText('As senhas devem ter no mínimo 6 caracteres.');
  expect(requests).toBe(0);
  await password.fill('123456');
  await confirmation.fill('123456');
  await auth.getByLabel('Nome Completo').fill('Cliente Teste');
  await auth.getByLabel('CPF', { exact: true }).fill('12345678909');
  await auth.getByLabel('E-mail', { exact: true }).fill('cliente@example.com');
  await auth.getByLabel('CEP', { exact: true }).fill('01001000');
  await expect(auth.getByLabel('Rua / Avenida')).toHaveValue('Rua Teste');
  await auth.getByLabel('Número', { exact: true }).fill('12');
  await submit.click();
  await expect(auth).toHaveCount(0);
  expect(requests).toBe(1);
  expect(submittedPassword).toBe('123456');
});
